In [21]:
import pandas as pd 
import numpy as np

In [38]:
def get_count_matrix(Cropus):

    bigrams = [] 
    vocabs = []
    count_matrix_dict = {}

    for i in range(len(Cropus)-3+1):

        trigram = tuple(Cropus[i:i+3])
        # print(trigram)

        bigram = trigram[0:-1]
        if not bigram in bigrams:
            bigrams.append(bigram)
        
        vocab = trigram[2]
        if not vocab in vocabs:
            vocabs.append(vocab)

        if (bigram,vocab) in count_matrix_dict:
            count_matrix_dict[(bigram,vocab)] += 1
        else:
            count_matrix_dict[(bigram,vocab)] = 1

    # print(count_matrix_dict)
    count_matrix = np.zeros((len(bigrams),len(vocabs)))
    for keys, count in count_matrix_dict.items():
        # print(keys,count)
        # print(bigrams.index(keys[0]))
        count_matrix[bigrams.index(keys[0]),vocabs.index(keys[1]) ] = count

    count_matrix = pd.DataFrame(count_matrix, index=bigrams, columns=vocabs)
    return count_matrix


corpus = ['i', 'am', 'happy', 'because', 'i', 'am', 'learning', '.']
count_matrix = get_count_matrix(corpus)
count_matrix

                  happy  because    i   am  learning    .
(i, am)             1.0      0.0  0.0  0.0       1.0  0.0
(am, happy)         0.0      1.0  0.0  0.0       0.0  0.0
(happy, because)    0.0      0.0  1.0  0.0       0.0  0.0
(because, i)        0.0      0.0  0.0  1.0       0.0  0.0
(am, learning)      0.0      0.0  0.0  0.0       0.0  1.0

In [41]:
row_sum = count_matrix.sum(axis=1)
row_sum

(i, am)             2.0
(am, happy)         1.0
(happy, because)    1.0
(because, i)        1.0
(am, learning)      1.0
dtype: float64

In [44]:
Prob_matrix = count_matrix.div(row_sum, axis=0)

In [45]:
Prob_matrix

                  happy  because    i   am  learning    .
(i, am)             0.5      0.0  0.0  0.0       0.5  0.0
(am, happy)         0.0      1.0  0.0  0.0       0.0  0.0
(happy, because)    0.0      0.0  1.0  0.0       0.0  0.0
(because, i)        0.0      0.0  0.0  1.0       0.0  0.0
(am, learning)      0.0      0.0  0.0  0.0       0.0  1.0